name: Deploy Site to Github Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: '0'
      - name: Checkout
        run: |
          git clone --depth 1 https://github.com/monochromer/monochromer.github.io.git .
          git fetch --unshallow

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build
        env:
          NODE_ENV: 'production'

      - name: Precompress static files
        run: npx @web-alchemy/web-compressor --input='./dist'

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4